name: Run pytest
on:
  push:
    branches: master
  pull_request:
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
    steps:
      - uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: |
          pip install poetry
          poetry config virtualenvs.create false
          poetry install
          poetry run pytest
        shell: bash
